# REMOVE OLD VERSION

- set_fact: update_version="False"

- name: check if older version installed
  stat:
    path: /etc/nginx/sites-enabled/screenshot.conf
  register: oldVersion_s

- name: check if older version installed v2
  stat:
    path: /usr/bin/raspi2png
  register: raspi2png_s

- set_fact: old_version="{{oldVersion_s.stat.exists}}"

- set_fact: raspi2pngNot="{{raspi2png_s.stat.exists}}"

- set_fact: update_version="True"
  when: old_version

- name: Remove old screenshot script
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - /home/pi/screenshot.sh
    - /home/pi/screenshot.log
    - /var/www/html/screen/
    - /home/pi/screenshot.sh
    - /etc/nginx/sites-enabled/screenshot.conf
    - /var/www/html/addon/screen/loading.png
  when: update_version

- name: Remove old image
  file:
    state: absent
    path: "/var/www/html/addon/screen/loading.png"
  when: not raspi2pngNot

- name: Remove old packages
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - x11-apps
    - imagemagick
  when: not raspi2pngNot

- name: remove crontab
  command: crontab -r
  when: not raspi2pngNot
  ignore_errors: yes

# START INSTALL
- name: Mount screen folder
  mount:
    path: /var/www/html/addon/screen
    src: tmpfs
    fstype: tmpfs
    opts: nodev,nosuid,size=25M
    state: mounted

- name: Install packages
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
    - libpng12-dev

- name: Copy raspi2png
  copy:
    src: raspi2png
    dest: /tmp

- name: Build raspi2png
  make:
    chdir: /tmp/raspi2png

- name: Run 'install' target as root
  make:
    chdir: /tmp/raspi2png
    target: install
  become: yes

- name: Copy screenshot.sh
  copy:
    src: screenshot.sh
    dest: /usr/bin/screenshot.sh
    owner: pi
    group: pi
    mode: 0755

- name: Copy index.html
  copy:
    src: index.html
    dest: /var/www/html/addon/index.html
    owner: www-data
    group: www-data
    mode: 0644

- name: Copy booting image
  copy:
    src: booting.png
    dest: /var/www/html/addon/booting.png
    owner: www-data
    group: www-data
    mode: 0644

- name: Copy error image
  copy:
    src: error.png
    dest: /var/www/html/addon/error.png
    owner: www-data
    group: www-data
    mode: 0644

- name: Crontab for screenshot.sh
  cron:
    name: "Crontab for screenshot.sh"
    special_time: reboot
    job: "sleep 20 && /usr/bin/screenshot.sh >> /var/log/screenshot.log 2>1"
