# Check older versions

- set_fact: update_version="False"

- name: check if older version installed
  stat:
    path: /etc/nginx/sites-enabled/screenshot.conf
  register: oldVersion_s

- set_fact: old_version="{{oldVersion_s.stat.exists}}"

- set_fact: update_version="True"
  when: old_version

- name: Remove old packages
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - nginx
  when: update_version

- name: Install packages
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
    - nginx-light

- name: Copy addon.conf
  copy:
    src: addon.conf
    dest: /etc/nginx/sites-enabled/addon.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart-nginx

- file:
    path: /var/www/html/addon
    state: directory
    owner: www-data
    group: www-data
    recurse: yes

- name: Copy monitor.txt
  copy:
    src: monitor.txt
    dest: /var/www/html/addon/monitor.txt
    owner: www-data
    group: www-data
    mode: 0644
